/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MeOutingsRouteImport } from './routes/me.outings'
import { Route as MeProfileRouteImport } from './routes/me.profile'
import { Route as OutingsIdRouteImport } from './routes/outings.$id'
import { Route as OutingsNewRouteImport } from './routes/outings.new'
import { Route as OutingsIdEditRouteImport } from './routes/outings_.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MeOutingsRoute = MeOutingsRouteImport.update({
  id: '/me/outings',
  path: '/me/outings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsIdRoute = OutingsIdRouteImport.update({
  id: '/outings/$id',
  path: '/outings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsNewRoute = OutingsNewRouteImport.update({
  id: '/outings/new',
  path: '/outings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsIdEditRoute = OutingsIdEditRouteImport.update({
  id: '/outings_/$id/edit',
  path: '/outings/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me/outings': typeof MeOutingsRoute
  '/me/profile': typeof MeProfileRoute
  '/outings/$id': typeof OutingsIdRoute
  '/outings/new': typeof OutingsNewRoute
  '/outings/$id/edit': typeof OutingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me/outings': typeof MeOutingsRoute
  '/me/profile': typeof MeProfileRoute
  '/outings/$id': typeof OutingsIdRoute
  '/outings/new': typeof OutingsNewRoute
  '/outings/$id/edit': typeof OutingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/me/outings': typeof MeOutingsRoute
  '/me/profile': typeof MeProfileRoute
  '/outings/$id': typeof OutingsIdRoute
  '/outings/new': typeof OutingsNewRoute
  '/outings_/$id/edit': typeof OutingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/me/outings'
    | '/me/profile'
    | '/outings/$id'
    | '/outings/new'
    | '/outings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/me/outings'
    | '/me/profile'
    | '/outings/$id'
    | '/outings/new'
    | '/outings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/me/outings'
    | '/me/profile'
    | '/outings/$id'
    | '/outings/new'
    | '/outings_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MeOutingsRoute: typeof MeOutingsRoute
  MeProfileRoute: typeof MeProfileRoute
  OutingsIdRoute: typeof OutingsIdRoute
  OutingsNewRoute: typeof OutingsNewRoute
  OutingsIdEditRoute: typeof OutingsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/outings': {
      id: '/me/outings'
      path: '/me/outings'
      fullPath: '/me/outings'
      preLoaderRoute: typeof MeOutingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings/$id': {
      id: '/outings/$id'
      path: '/outings/$id'
      fullPath: '/outings/$id'
      preLoaderRoute: typeof OutingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings/new': {
      id: '/outings/new'
      path: '/outings/new'
      fullPath: '/outings/new'
      preLoaderRoute: typeof OutingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings_/$id/edit': {
      id: '/outings_/$id/edit'
      path: '/outings/$id/edit'
      fullPath: '/outings/$id/edit'
      preLoaderRoute: typeof OutingsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MeOutingsRoute: MeOutingsRoute,
  MeProfileRoute: MeProfileRoute,
  OutingsIdRoute: OutingsIdRoute,
  OutingsNewRoute: OutingsNewRoute,
  OutingsIdEditRoute: OutingsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
